package libreria;
// Generated Mar 12, 2018 10:47:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Editorial generated by hbm2java
 */
public class Editorial  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set libros = new HashSet(0);

    public Editorial() {
    }

	
    public Editorial(String nombre) {
        this.nombre = nombre;
    }
    public Editorial(String nombre, Set libros) {
       this.nombre = nombre;
       this.libros = libros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }




}


