package parkingSystem;
// Generated Mar 11, 2018 6:38:33 PM by Hibernate Tools 4.3.1



/**
 * Parking generated by hbm2java
 */
public class ParkingSpot  implements java.io.Serializable {


     private String matricula;
     private String modelo;
     // Nota: Hibernate ha generado entrada como int porque en la base de datos es un Integer, 
     // pero se ha tenido que cambiar a String para que coincida con la clase del ejercicio anterior, 
     // donde está definido como String, para no tener que cambiar ni castear todos los métodos relacionados 
     // con esta clase construidos hasta ahora. Por este motivo, tambien se han
     // renombrado los metodos getter y setter de entrada y salida para que incluyan "hora".
     private int entrada;
     private String salida;
     private int tiempoPermitido;

    public ParkingSpot() {
    }

    public ParkingSpot(String matricula, String modelo, int entrada, String salida, int tiempoPermitido) {
       this.matricula = matricula;
       this.modelo = modelo;
       this.entrada = entrada;
       this.salida = salida;
       this.tiempoPermitido = tiempoPermitido;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public int getHoraEntrada() {
        return this.entrada;
    }
    
    public void setHoraEntrada(int entrada) {
        this.entrada = entrada;
    }
    public String getHoraSalida() {
        return this.salida;
    }
    
    public void setHoraSalida(String salida) {
        this.salida = salida;
    }
    public int getTiempoPermitido() {
        return this.tiempoPermitido;
    }
    
    public void setTiempoPermitido(int tiempoPermitido) {
        this.tiempoPermitido = tiempoPermitido;
    }




}


