package libreria;
// Generated Apr 29, 2018 5:19:37 PM by Hibernate Tools 4.3.1



/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private Integer id;
     private String autor;
     private String titulo;
     private float precio;
     private int isbn;
     private int editorialid;
     private int cantidad;

    public Libro() {
    }

    public Libro(String autor, String titulo, float precio, int isbn, int editorialid) {
       this.autor = autor;
       this.titulo = titulo;
       this.precio = precio;
       this.isbn = isbn;
       this.editorialid = editorialid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }
    public int getEditorialid() {
        return this.editorialid;
    }
    
    public void setEditorialid(int editorialid) {
        this.editorialid = editorialid;
    }
    
    public void incrementaCantidad()
    {
        this.cantidad++;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    



}


