package model;
// Generated Mar 11, 2018 6:38:33 PM by Hibernate Tools 4.3.1

/**
 * Parking generated by hbm2java
 */
public class Parking implements java.io.Serializable {

    private String matricula;
    private String modelo;
    /* Entrada y salida se guardan como en la bbdd, es decir, un int que representa horas*60+minutos, a diferencia del problema 4, 
     *  donde se guardan como un string tal que hh:mm
     */
    private int entrada;
    private String salida;
    private int tiempoPermitido;

    public Parking() {
    }

    public Parking(String matricula, String modelo, int entrada, String salida, int tiempoPermitido) {
        this.matricula = matricula;
        this.modelo = modelo;
        this.entrada = entrada;
        this.salida = salida;
        this.tiempoPermitido = tiempoPermitido;
    }

    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public int getEntrada() {
        return this.entrada;
    }

    public void setEntrada(int entrada) {
        this.entrada = entrada;
    }

    public String getSalida() {
        return this.salida;
    }

    public void setSalida(String salida) {
        this.salida = salida;
    }

    public int getTiempoPermitido() {
        return this.tiempoPermitido;
    }

    public void setTiempoPermitido(int tiempoPermitido) {
        this.tiempoPermitido = tiempoPermitido;
    }

}
